"""Assemble an `ExtractedInvoice` from the page, with no model involved.

This is a drop-in replacement for `llm.extract_invoice`: same keyword
arguments, same `ExtractionResult`. Everything downstream — persistence, the
validation rules, party matching, brokerage — is unchanged, so a bill read
here is checked exactly as hard as a bill read by a model.

The one number that must not be wrong is the invoice total, so it is not read
from a single place. The QR, the spelled-out words and the printed figure are
three independent statements of it, and the value two of them agree on is the
one that is filed.
"""
from __future__ import annotations

import logging
import re
import time
from decimal import Decimal
from pathlib import Path

from app.extraction.layout import PageLayout, read_layout
from app.extraction.pdf_text import score_text
from app.extraction.result import ExtractionError, ExtractionResult
from app.extraction.local import fields, glyphs, table, totals
from app.extraction.local.qr import EInvoiceQR, QRFindings, read_qr
from app.extraction.normalize import (
    normalize_hsn, parse_date, pan_from_gstin, state_from_gstin,
)
from app.schemas import (
    ExtractedBank, ExtractedCharge, ExtractedEwayBill, ExtractedInvoice,
    ExtractedLine, ExtractedParty, ExtractedTaxSummaryRow, FieldNote,
    UnmappedField,
)
from app.validation.rules import NOT_CAPTURED
from app.validation.words import words_to_number

log = logging.getLogger(__name__)

READER_VERSION = "local-1"

# Two figures agreeing within a rupee are the same figure.
AGREE_TOL = Decimal("1.0")

INVOICE_NO_LABELS = ("invoice no", "invoice no.", "invoice number", "bill no",
                     "inv no")
INVOICE_DATE_LABELS = ("dated", "invoice dt", "invoice date", "date")
BROKER_LABELS = ("broker name", "broker", "representative", "agent", "through",
                 "dalal", "broker's name")
EWAY_LABELS = ("e-way bill no", "e-way bill no.", "eway bill no", "e way bill no",
               "eway bill no.")
TERMS_LABELS = ("mode/terms of payment", "terms of payment", "payment terms")
POS_LABELS = ("place of supply",)
ACK_NO_LABELS = ("ack no", "ack no.")
ACK_DATE_LABELS = ("ack date", "ack dt")
# Not a bare 'bank': the totals block is headed 'Bank Details', which appears
# earlier on the page and would answer with the word 'Details'.
BANK_NAME_LABELS = ("bank name", "name of bank", "bankers")
ACCOUNT_LABELS = ("a/c no", "account no", "account number", "a/c no.")
IFSC_LABELS = ("ifsc code", "ifsc", "branch & ifs code", "ifs code")
BRANCH_LABELS = ("branch name", "branch & ifs code", "branch and ifs code", "branch")
REMARKS_LABELS = ("remarks", "remark", "narration")

# Printed on bills, but with no home in the schema. Captured verbatim so that
# nothing on the document is silently dropped — the review screen can show
# what was read and ignored.
EXTRA_LABELS = {
    "Previous Balance": ("previous balance",),
    "Current Balance": ("current balance",),
    "Ship From": ("ship from",),
    "Dispatched through": ("dispatched through",),
    "Destination": ("destination",),
    "Terms of Delivery": ("terms of delivery",),
    "Delivery Note": ("delivery note",),
    "Buyer's Order No.": ("buyer's order no", "buyers order no"),
    "Reference No. & Date.": ("reference no. & date.",),
    "Other References": ("other references",),
    "Representative": ("representative",),
    "Buyer's PAN": ("buyer's pan no", "buyer's pan"),
    "Tax Amount (in words)": ("tax amount (in words)", "tax amt in words"),
}

# What each of these is worth checking for, and the evidence that the bill
# carries one at all.
CAPTURE_CHECKS = (
    ("a transporter", ("transporter id", "transporter name", "transporter"),
     lambda inv: bool(inv.eway_bill and (inv.eway_bill.transporter_name
                                         or inv.eway_bill.transporter_id))),
    ("a vehicle number", ("vehicle no", "vehicle no.", "vehicle number"),
     lambda inv: bool(inv.eway_bill and inv.eway_bill.vehicle_no)),
    ("a broker", ("broker name", "broker", "representative"),
     lambda inv: bool(inv.broker_name)),
    ("bank details", ("bank name", "a/c no", "account no", "ifsc code"),
     lambda inv: bool(inv.bank and (inv.bank.account_number or inv.bank.ifsc))),
    ("a place of supply", ("place of supply",), lambda inv: bool(inv.place_of_supply)),
    ("payment terms", ("mode/terms of payment", "terms of payment"),
     lambda inv: bool(inv.payment_terms)),
)


# The e-way bill annexure, which repeats the consignment's transport details.
EWAY_FIELD_LABELS = {
    "mode": ("mode",),
    "generated_date": ("generated date",),
    "generated_by": ("generated by",),
    "valid_upto": ("valid upto", "valid up to"),
    "supply_type": ("supply type",),
    "transaction_type": ("transaction type",),
    "approx_distance_km": ("approx distance",),
    "transporter_id": ("transporter id", "transporter gstin", "transin"),
    "transporter_name": ("transporter name", "name"),
    "vehicle_no": ("vehicle no", "vehicle no.", "vehicle number"),
    "vehicle_from": ("from",),
    "cewb_no": ("cewb no", "cewb no."),
}


# --------------------------------------------------------------------------
# Small parsers
# --------------------------------------------------------------------------


def _num(text: str) -> float | None:
    value = totals.parse_amount(text)
    return float(value) if value is not None else None


def _split_quantity(text: str) -> tuple[float | None, str | None]:
    """'4,500.000 KGS' -> (4500.0, 'KGS')."""
    if not text:
        return None, None
    parts = text.split()
    number = uom = None
    for part in parts:
        value = totals.parse_amount(part)
        if value is not None and number is None:
            number = float(value)
        elif any(c.isalpha() for c in part) and uom is None:
            uom = part.strip().upper()
    return number, uom


def _percent(text: str) -> float | None:
    if not text:
        return None
    return _num(text.replace("%", " "))


def _first(*values):
    for value in values:
        if value not in (None, ""):
            return value
    return None


# --------------------------------------------------------------------------
# Reconciling the invoice total
# --------------------------------------------------------------------------


def _reconcile(candidates: dict[str, Decimal]) -> tuple[Decimal | None, list[str]]:
    """The figure the most sources agree on, and who agreed.

    With three statements of the total available, a lone disagreeing reading
    loses. With only one statement there is nothing to reconcile — it is
    returned, and the arithmetic rules downstream decide whether it holds.
    """
    if not candidates:
        return None, []
    best_value, best_sources = None, []
    for name, value in candidates.items():
        agree = [other for other, v in candidates.items()
                 if abs(v - value) <= AGREE_TOL]
        if len(agree) > len(best_sources):
            best_value, best_sources = value, agree
    return best_value, sorted(best_sources)


# --------------------------------------------------------------------------
# Parties
# --------------------------------------------------------------------------


def _party(name: str | None, gstin: str | None, address_lines: list[str],
           pages: list[PageLayout]) -> ExtractedParty:
    state_code, state_name = state_from_gstin(gstin) if gstin else (None, None)
    address = ", ".join(
        line for line in address_lines
        if line and not fields.GSTIN_RE.search(line)
        and not fields.STATE_NAME_RE.search(line)
    ) or None

    pincode = None
    for line in address_lines:
        hit = fields.PINCODE_RE.search(line)
        if hit:
            pincode = hit.group(1)
            break
    email = None
    for line in address_lines:
        hit = fields.EMAIL_RE.search(line)
        if hit:
            email = hit.group(1)
            break

    return ExtractedParty(
        name=name,
        gstin=gstin,
        pan=pan_from_gstin(gstin) if gstin else None,
        address=address,
        state_name=state_name,
        state_code=state_code,
        pincode=pincode,
        email=email,
    )


def _pick_block(blocks: list[fields.PartyBlock], role: str) -> fields.PartyBlock | None:
    for block in blocks:
        if block.role == role and (block.gstin or block.name):
            return block
    return None


# --------------------------------------------------------------------------
# The reader
# --------------------------------------------------------------------------


def extract_invoice(
    *,
    doc_path: Path,
    mime_type: str = "application/pdf",
    page_images: list[Path] | None = None,
    text_layer: str = "",
    ocr_text: str = "",
    text_quality: float = 0.0,
    route: str = "text_layer",
    page_count: int = 1,
    model: str | None = None,
) -> ExtractionResult:
    """Read one bill off its own text layer."""
    started = time.time()
    pages = read_layout(doc_path)
    findings: QRFindings = read_qr(doc_path)
    qr = findings.einvoice
    recovered = False

    # A computer-generated PDF can still be unreadable: some packages embed
    # subset fonts with every trace of unicode stripped. The glyph outlines
    # survive, so the characters can be recovered from their shapes — seeded
    # with what the QR already states, which settles any shape the outline
    # table does not recognise.
    if not pages or score_text(fields.document_text(pages)) < 0.6:
        known = [qr.seller_gstin, qr.buyer_gstin, qr.doc_no, qr.irn] if qr else []
        decoded = glyphs.read_decoded_layout(doc_path, known=[k for k in known if k])
        if decoded and score_text(fields.document_text(decoded)) >= 0.6:
            log.info("%s: recovered the text layer from glyph outlines", doc_path.name)
            pages, recovered = decoded, True

    if not pages and qr is None:
        raise ExtractionError(
            f"{doc_path.name} has no usable text layer and no readable QR code."
        )

    doc_text = fields.document_text(pages) if pages else ""
    # A mojibake text layer cannot confirm the QR, but neither can it
    # contradict it — and on those bills the QR is the only reading there is.
    text_usable = bool(doc_text.strip()) and score_text(doc_text) >= 0.6
    qr_trusted = bool(qr) and (
        fields.qr_is_consistent(qr, doc_text) if text_usable else True
    )
    notes: list[FieldNote] = []
    if recovered:
        notes.append(FieldNote(
            field_path="seller.name",
            issue=("This PDF's fonts carry no character map; the text was "
                   "recovered from the glyph outlines and should be spot-checked."),
        ))
    if qr and not text_usable:
        notes.append(FieldNote(
            field_path="seller.name",
            issue=("The PDF's text layer does not decode, so only the QR code "
                   "could be read. Line items and totals are missing."),
        ))
    if qr and text_usable and not fields.qr_is_consistent(qr, doc_text):
        notes.append(FieldNote(
            field_path="irn",
            issue=("The QR code describes a different document from the one "
                   "printed on the page, so nothing from it was used."),
            printed_text=f"{qr.doc_no} dated {qr.doc_date} for {qr.total_value}",
        ))

    invoice = _build(pages, qr if qr_trusted else None, findings, notes, doc_path)
    duration_ms = int((time.time() - started) * 1000)

    log.info("read %s locally in %dms (confidence %.2f)",
             doc_path.name, duration_ms, invoice.overall_confidence)

    return ExtractionResult(
        invoice=invoice,
        model="local-text-layer",
        prompt_version=READER_VERSION,
        input_tokens=0,
        output_tokens=0,
        duration_ms=duration_ms,
        raw=invoice.model_dump(mode="json"),
        stop_reason="end_turn",
    )


def _build(pages: list[PageLayout], qr: EInvoiceQR | None, findings: QRFindings,
           notes: list[FieldNote], doc_path: Path) -> ExtractedInvoice:
    page1 = pages[0] if pages else None
    blocks = fields.party_blocks(page1) if page1 else []
    letterhead = fields.letterhead_block(page1) if page1 else fields.PartyBlock("seller")

    buyer_block = _pick_block(blocks, "buyer")
    consignee_block = _pick_block(blocks, "consignee")

    seller_gstin = _first(
        fields.seller_gstin(pages, blocks, letterhead) if pages else None,
        qr.seller_gstin if qr else None,
    )
    buyer_gstin = _first(
        buyer_block.gstin if buyer_block else None,
        qr.buyer_gstin if qr else None,
    )

    seller_name = letterhead.name
    if seller_name and "(cid:" in seller_name:
        seller_name = None
    seller = _party(seller_name, seller_gstin, letterhead.lines, pages)
    buyer = _party(
        buyer_block.name if buyer_block else None,
        buyer_gstin,
        buyer_block.lines if buyer_block else [],
        pages,
    )
    consignee = None
    if consignee_block and consignee_block.gstin != buyer_gstin:
        consignee = _party(consignee_block.name, consignee_block.gstin,
                           consignee_block.lines, pages)

    lines, charges, tax_rows_seen = _read_table(pages)
    summary = _read_tax_summary(pages)
    figures = totals.read_totals(pages) if pages else {}

    printed_words = totals.read_amount_in_words(pages) if pages else None
    grand_total, agreed = _grand_total(qr, printed_words, figures)

    taxable = figures.get("taxable_value")
    if taxable is None and summary:
        taxable = sum((Decimal(str(r.taxable_value)) for r in summary
                       if r.taxable_value is not None), Decimal(0)) or None

    igst = figures.get("igst_amount") or tax_rows_seen.get("igst")
    cgst = figures.get("cgst_amount") or tax_rows_seen.get("cgst")
    sgst = figures.get("sgst_amount") or tax_rows_seen.get("sgst")

    charge_total = sum(
        (Decimal(str(c.amount)) for c in charges
         if c.kind not in ("discount", "round_off")),
        Decimal(0),
    )
    discount_total = sum(
        (abs(Decimal(str(c.amount))) for c in charges if c.kind == "discount"),
        Decimal(0),
    )
    round_off = figures.get("round_off")
    if round_off is None:
        round_off = next((Decimal(str(c.amount)) for c in charges
                          if c.kind == "round_off"), None)

    if round_off is not None and not any(c.kind == "round_off" for c in charges):
        charges.append(ExtractedCharge(
            label="Round Off", kind="round_off", amount=float(round_off)))

    if taxable is None and lines:
        # Not every layout prints a taxable value or an HSN summary. Rows plus
        # the charges that are taxed with them reconstruct it, and the
        # validator checks the result against the tax actually charged.
        taxable = sum(
            (Decimal(str(l.taxable_amount)) for l in lines
             if l.taxable_amount is not None), Decimal(0)
        ) + sum((Decimal(str(c.amount)) for c in charges
                 if c.kind not in ("round_off",)), Decimal(0))

    invoice_number = _first(
        fields.label_value(pages, INVOICE_NO_LABELS) if pages else None,
        qr.doc_no if qr else None,
    )
    invoice_date = _first(
        _iso(fields.label_value(pages, INVOICE_DATE_LABELS)) if pages else None,
        _iso(qr.doc_date) if qr else None,
    )

    eway_no = _first(
        _digits(fields.label_value(pages, EWAY_LABELS)) if pages else None,
        findings.eway.eway_bill_no if findings.eway else None,
    )
    eway = _read_eway(pages, eway_no)

    subtotal = sum((Decimal(str(l.taxable_amount)) for l in lines
                    if l.taxable_amount is not None), Decimal(0)) or None

    invoice = ExtractedInvoice(
        document_type=_document_type(pages),
        invoice_number=invoice_number,
        invoice_date=invoice_date,
        irn=_first(fields.find_irn(pages) if pages else None, qr.irn if qr else None),
        ack_no=_first(fields.label_value(pages, ACK_NO_LABELS) if pages else None),
        ack_date=_iso(fields.label_value(pages, ACK_DATE_LABELS)) if pages else None,
        seller=seller,
        buyer=buyer,
        consignee=consignee,
        broker_name=_broker(pages),
        place_of_supply=fields.label_value(pages, POS_LABELS) if pages else None,
        payment_terms=fields.label_value(pages, TERMS_LABELS) if pages else None,
        lines=lines,
        charges=charges,
        tax_summary=summary,
        subtotal=_f(subtotal),
        discount_total=_f(discount_total) or None,
        taxable_value=_f(taxable),
        cgst_amount=_f(cgst),
        sgst_amount=_f(sgst),
        igst_amount=_f(igst),
        tcs_amount=_f(figures.get("tcs_amount")),
        other_charges=_f(charge_total) or None,
        round_off=_f(round_off),
        grand_total=_f(grand_total),
        amount_in_words=printed_words,
        total_quantity=_f(sum((Decimal(str(l.quantity)) for l in lines
                               if l.quantity is not None), Decimal(0))) or None,
        total_quantity_uom=next((l.uom for l in lines if l.uom), None),
        total_bags=_f(sum((Decimal(str(l.bags)) for l in lines
                           if l.bags is not None), Decimal(0))) or None,
        eway_bill=eway,
        bank=_bank(pages),
        remarks=fields.label_value(pages, REMARKS_LABELS) if pages else None,
        field_notes=notes,
        overall_confidence=_confidence(
            agreed=agreed, lines=lines, charges=charges, taxable=taxable,
            seller=seller, buyer=buyer, qr=qr,
        ),
        vendor_format_hint=_format_hint(seller_gstin),
    )
    invoice.unmapped_fields = _extras(pages) + _gaps(pages, invoice)
    return invoice


def _extras(pages: list[PageLayout]) -> list[UnmappedField]:
    """Values the bill prints that the schema has nowhere to put."""
    out: list[UnmappedField] = []
    for label, aliases in EXTRA_LABELS.items():
        value = _clean_value(fields.label_value(pages, aliases) if pages else None)
        if value and len(value) < 120:
            out.append(UnmappedField(label=label, value=value, section="printed"))
    return out


_CID_RE = re.compile(r"\(cid:\d+\)")


def _clean_value(text: str | None) -> str | None:
    """Drop glyphs that never decoded, so they are not filed as content."""
    if not text:
        return None
    return " ".join(_CID_RE.sub(" ", text).split()).strip(" :&.-") or None


def _gaps(pages: list[PageLayout], invoice: ExtractedInvoice) -> list[UnmappedField]:
    """Things the page evidently carries that did not make it into the record.

    A label on the page with nothing filed against it is the only warning
    available for a field no arithmetic can check. Without this a bill can
    reconcile perfectly with its transporter missing, and post clean.
    """
    if not pages:
        return []
    out: list[UnmappedField] = []
    for description, aliases, captured in CAPTURE_CHECKS:
        if captured(invoice):
            continue
        if fields.label_value(pages, aliases, below=True):
            out.append(UnmappedField(
                label=description, value=description, section=NOT_CAPTURED))
    return out


def _f(value) -> float | None:
    return float(value) if value is not None else None


def _iso(text: str | None) -> str | None:
    parsed = parse_date(text) if text else None
    return parsed.isoformat() if parsed else None


def _digits(text: str | None) -> str | None:
    if not text:
        return None
    digits = "".join(c for c in text if c.isdigit())
    return digits or None


def _document_type(pages: list[PageLayout]) -> str:
    text = " ".join(line.text.lower() for line in pages[0].lines[:6]) if pages else ""
    for needle, kind in (
        ("credit note", "credit_note"), ("debit note", "debit_note"),
        ("proforma", "proforma_invoice"), ("bill of supply", "bill_of_supply"),
        ("delivery challan", "delivery_challan"),
    ):
        if needle in text:
            return kind
    return "tax_invoice"


def _broker(pages: list[PageLayout]) -> str | None:
    raw = fields.label_value(pages, BROKER_LABELS) if pages else None
    if not raw:
        return None
    # Some bills print the brokerage rate beside the name — 'NILESH BHAI
    # 0.5%'. Only that trailing rate is removed: a broker's own code, as in
    # 'Nileshbhai C38', is part of the name.
    cleaned = " ".join(raw.split())
    if "%" in cleaned:
        cleaned = cleaned.split("%")[0].strip()
        parts = cleaned.split()
        if parts and totals.parse_amount(parts[-1]) is not None:
            cleaned = " ".join(parts[:-1])
    return cleaned.strip(" .:-") or None


TRANSPORT_HEADING_RE = re.compile(r"^\d*\.?\s*(transportation|transporter|vehicle)\s+details",
                                  re.I)


def _below_heading(pages: list[PageLayout], heading: re.Pattern) -> list[PageLayout]:
    """The part of each page that sits under a given section heading."""
    out: list[PageLayout] = []
    for page in pages:
        lines = page.lines
        start = next((i for i, line in enumerate(lines)
                      if heading.match(line.text.strip())), None)
        if start is None:
            continue
        words = [w for line in lines[start + 1:] for w in line.words]
        if words:
            out.append(PageLayout(page.page_no, page.width, page.height, words))
    return out


def _read_eway(pages: list[PageLayout], eway_no: str | None) -> ExtractedEwayBill | None:
    """Transport details, read off the e-way bill annexure.

    Read only from the annexure pages: labels as generic as 'Name' and 'From'
    mean something quite different on the invoice itself, and the transporter
    is the one party on the bill that no other page names.
    """
    annexures = [p for p in pages if table.is_annexure(p)]
    if not annexures and not eway_no:
        return None

    # 'Name' and 'From' are far too common to look for page-wide: the goods
    # table on the same page is headed 'Product Name & Desc', and the address
    # block is headed 'From'. Both are read only below the transport heading.
    transport = _below_heading(annexures, TRANSPORT_HEADING_RE)

    values: dict[str, str | None] = {}
    for name, labels in EWAY_FIELD_LABELS.items():
        scope = transport if name in ("transporter_name", "vehicle_from") else annexures
        values[name] = fields.label_value(scope, labels) if scope else None

    distance = _num((values.get("approx_distance_km") or "").replace("KM", " "))
    return ExtractedEwayBill(
        eway_bill_no=eway_no,
        generated_date=_iso(values.get("generated_date")),
        generated_by=values.get("generated_by"),
        valid_upto=_iso(values.get("valid_upto")),
        mode=(values.get("mode") or "").split("-")[-1].strip() or None,
        approx_distance_km=distance,
        supply_type=values.get("supply_type"),
        transaction_type=values.get("transaction_type"),
        transporter_id=values.get("transporter_id"),
        transporter_name=values.get("transporter_name"),
        vehicle_no=(values.get("vehicle_no") or "").replace(" ", "") or None,
        vehicle_from=values.get("vehicle_from"),
        cewb_no=values.get("cewb_no"),
    )


def _bank(pages: list[PageLayout]) -> ExtractedBank | None:
    if not pages:
        return None
    ifsc = None
    for found in fields.find_all(pages, fields.IFSC_RE):
        ifsc = found.value
        break
    branch = fields.label_value(pages, BRANCH_LABELS)
    if branch and "&" in branch:
        # Some bills share one field: 'Branch & IFS Code : X & IFSC'.
        branch = branch.split("&")[0].strip() or None
    bank = ExtractedBank(
        bank_name=fields.label_value(pages, BANK_NAME_LABELS),
        account_number=_digits(fields.label_value(pages, ACCOUNT_LABELS)),
        ifsc=ifsc,
        branch=branch,
    )
    return bank if any(bank.model_dump().values()) else None


def _format_hint(gstin: str | None) -> str | None:
    return f"local-{gstin}" if gstin else None


def _grand_total(qr, printed_words, figures) -> tuple[Decimal | None, list[str]]:
    candidates: dict[str, Decimal] = {}
    if qr and qr.total_value is not None:
        candidates["qr"] = Decimal(str(qr.total_value))
    if printed_words:
        spelled = words_to_number(printed_words)
        if spelled is not None:
            candidates["words"] = Decimal(str(spelled))
    if figures.get("grand_total") is not None:
        candidates["printed"] = figures["grand_total"]
    return _reconcile(candidates)


def _read_table(pages: list[PageLayout]):
    lines: list[ExtractedLine] = []
    charges: list[ExtractedCharge] = []
    taxes: dict[str, Decimal] = {}

    for page in pages:
        if table.is_annexure(page):
            continue
        header = table.find_header(page)
        if header is None:
            continue
        for row in table.read_rows(page, header):
            table.repair_quantity_columns(row)
            kind, charge_kind = table.classify(row)
            amount = totals.parse_amount(row.get("amount"))

            if kind == "total":
                # The totals strip restating a figure the invoice already
                # carries in a field of its own. Nothing to add.
                continue

            if kind == "tax":
                head = row.full_text.lower()
                for name in ("igst", "cgst", "sgst", "cess"):
                    if name in head.replace(" ", "") and amount is not None:
                        taxes[name] = amount
                continue

            if kind == "charge":
                if amount is None:
                    continue
                if charge_kind == "discount":
                    amount = -abs(amount)
                charges.append(ExtractedCharge(
                    label=" ".join(row.full_text.split())[:80] or (charge_kind or "charge"),
                    kind=charge_kind or "other",
                    amount=float(amount),
                    hsn=normalize_hsn(row.get("hsn")) or None,
                    tax_rate=_percent(row.get("tax_rate")),
                ))
                continue

            quantity, uom = _split_quantity(row.get("quantity"))
            bags, _ = _split_quantity(row.get("bags"))
            # Some layouts print '990.00' under Quantity and 'KGS' in a Unit
            # column of its own. The unit governs the quantity either way, and
            # without this the ledger shows a number with nothing after it.
            if uom is None:
                uom = (row.get("rate_uom") or "").strip().upper() or None
            description, extra_bags, brand = table.split_continuations(row)
            lines.append(ExtractedLine(
                line_no=int(_num(row.get("serial")) or len(lines) + 1),
                description=description,
                brand=brand,
                item_code=row.get("item_code") or None,
                item_remarks=row.get("item_remarks") or None,
                hsn=normalize_hsn(row.get("hsn")) or None,
                bags=bags if bags is not None else extra_bags,
                quantity=quantity,
                uom=uom,
                rate=_num(row.get("rate")),
                rate_uom=row.get("rate_uom") or None,
                discount_pct=_percent(row.get("discount")),
                taxable_amount=float(amount) if amount is not None else None,
                tax_rate=_percent(row.get("tax_rate")),
            ))
    return lines, charges, taxes


def _read_tax_summary(pages: list[PageLayout]) -> list[ExtractedTaxSummaryRow]:
    rows: list[ExtractedTaxSummaryRow] = []
    readable = [p for p in pages if not table.is_annexure(p)]
    for row in totals.read_tax_summary(readable):
        rows.append(ExtractedTaxSummaryRow(
            hsn=normalize_hsn(row.hsn) or None,
            taxable_value=_f(row.taxable_value),
            cgst_rate=_f(row.cgst_rate),
            cgst_amount=_f(row.cgst_amount),
            sgst_rate=_f(row.sgst_rate),
            sgst_amount=_f(row.sgst_amount),
            igst_rate=_f(row.igst_rate),
            igst_amount=_f(row.igst_amount),
            total_tax=_f(row.total_tax),
        ))
    return rows


def _confidence(*, agreed: list[str], lines, charges, taxable,
                seller: ExtractedParty, buyer: ExtractedParty,
                qr: EInvoiceQR | None) -> float:
    """How much of this reading was independently confirmed.

    Not a guess at how good the reader is — a count of the checks that
    actually passed on this document. A bill whose total is stated three times
    identically, whose rows add up to its taxable value and whose GSTINs both
    carry correct check digits has been verified about as far as a document
    can verify itself.
    """
    score = 0.5
    if len(agreed) >= 2:
        score += 0.20
    if lines:
        score += 0.05
        rows = sum((Decimal(str(l.taxable_amount)) for l in lines
                    if l.taxable_amount is not None), Decimal(0))
        extra = sum((Decimal(str(c.amount)) for c in charges
                     if c.kind != "round_off"), Decimal(0))
        if taxable is not None and min(
            abs(rows - Decimal(str(taxable))),
            abs(rows + extra - Decimal(str(taxable))),
        ) <= AGREE_TOL:
            score += 0.10
    if seller.gstin and buyer.gstin:
        score += 0.10
    if qr is not None:
        score += 0.05
    return round(min(score, 0.98), 2)
